# Generated by Django 3.2.7 on 2021-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_movies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
