# Generated by Django 3.2.7 on 2021-11-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_movies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
