# Generated by Django 3.2.7 on 2021-11-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_movies_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='name',
        ),
    ]
