# Generated by Django 3.2.7 on 2021-11-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_books_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='uniqueid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='uniqueid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uniqueid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
