# Generated by Django 3.2.7 on 2021-11-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_addtocart_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtowishlist',
            name='uniqueid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
