# Generated by Django 3.2.7 on 2021-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_addtowishlist_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
