# Generated by Django 3.2.7 on 2021-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_addtocart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
