# Generated by Django 3.2.7 on 2021-11-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_addtocart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='price',
        ),
    ]
