# Generated by Django 3.2.7 on 2021-11-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='uniqueid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
