# Generated by Django 3.2.7 on 2021-11-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20211106_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='product',
            new_name='name',
        ),
    ]
