# Generated by Django 3.2.7 on 2021-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_product_addtocart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
