# Generated by Django 3.2.7 on 2021-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20211106_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtowishlist',
            old_name='product',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='uniqueid',
        ),
        migrations.RemoveField(
            model_name='addtowishlist',
            name='uniqueid',
        ),
        migrations.AlterField(
            model_name='books',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
