# Generated by Django 3.2.7 on 2021-11-06 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
