# Generated by Django 3.2.7 on 2021-11-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
