# Generated by Django 3.2.7 on 2021-11-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
